### ISSUE TITLE
Indentation Issues

### ISSUE THREAD

**Issue by ercanersoy** [Atnode/MetaCache#1]
Hello Atnode,

MetaCache is a good project. I have looked some codes of this project.

I have seen indentation issues on **index.php** and **css/style.css**. I suggest space character instead of tab character.

Thanks for replying.

**Comment by Atnode** [comment]
Hello Ercan,

Thank you for reporting this issue.
I will correct this problem as soon as practicable.

Thank you again and best regards.

**Comment by Atnode** [comment]
Good news!
This is now fixed in the last commit.
Thank you again for reporting this issue.
Best regards.
